export adminGetAllCategories from 'src/admin/categories/adminGetAllCategories.js';
export CategoriesAdmin from 'src/admin/categories/CategoriesAdmin.vue';
export CategoryForm from 'src/admin/categories/CategoryForm.vue';
export CategoryItem from 'src/admin/categories/CategoryItem.vue';
export CreateCategory from 'src/admin/categories/CreateCategory.vue';
export EditCategory from 'src/admin/categories/EditCategory.vue';
export Categories1 from 'src/modules/categories/Categories1.vue';
export Categories2 from 'src/modules/categories/Categories2.vue';
export categoriesState from 'src/store/categories/categoriesState.js'