export Breadcrumbs from 'src/comp/Breadcrumbs.vue';
export Captcha from 'src/comp/Captcha.vue';
export CategoriesInput from 'src/comp/CategoriesInput.vue';
export LinksMenu from 'src/comp/LinksMenu.vue';
export MenuItem from 'src/comp/MenuItem.vue';
export PageWrapper from 'src/comp/PageWrapper.vue';
export PanelWrapper from 'src/comp/PanelWrapper.vue';
export wrapInPage from 'src/comp/wrapInPage.js';
export wrapInPanel from 'src/comp/wrapInPanel.js';
