export CreateMaterial from 'src/modules/material/CreateMaterial.vue';
export EditMaterial from 'src/modules/material/EditMaterial.vue';
export Material from 'src/modules/material/Material.vue';
export MaterialForm from 'src/modules/material/MaterialForm.vue';
export MaterialInline from 'src/modules/material/MaterialInline.vue';
export canDeleteMaterial from 'src/modules/material/methods/canDeleteMaterial.js';
export canRestoreMaterial from 'src/modules/material/methods/canRestoreMaterial.js';
export deleteMaterial from 'src/modules/material/methods/deleteMaterial.js';
export * from 'src/modules/material/methods/getWhereToAddMove.js';
export restoreMaterial from 'src/modules/material/methods/restoreMaterial.js'