export ChangeLink from 'modules/personal/ChangeLink'
export ChangeName from 'modules/personal/ChangeName'
export editInformationToolbar from 'modules/personal/editInformationToolbar'
export EditInformation from 'modules/personal/EditInformation'
export LoadPhoto from 'modules/personal/LoadPhoto'
export MyBanList from 'modules/personal/MyBanList'
export SettingsMenu from 'modules/personal/SettingsMenu'
export SettingsPage from 'modules/personal/SettingsPage'
export SettingsPanel from 'modules/personal/SettingsPanel'

