export ChangeLink from 'src/modules/personal/ChangeLink.vue';
export ChangeName from 'src/modules/personal/ChangeName.vue';
export EditInformation from 'src/modules/personal/EditInformation.vue';
export LoadPhoto from 'src/modules/personal/LoadPhoto.vue';
export MyBanList from 'src/modules/personal/MyBanList.vue';
export Sessions from 'src/modules/personal/Sessions.vue';
export SettingsMenu from 'src/modules/personal/SettingsMenu.vue';
export SettingsPage from 'src/modules/personal/SettingsPage.vue';
export SettingsPanel from 'src/modules/personal/SettingsPanel.vue';
