export adminModule from './admin'
export authModule from './auth'
export categoriesModule from './categories'
export layoutsModule from './layouts'
export menuModule from './menu'
export rootModule from './root'
export * from 'store/storeInstance'
