# Variables to build script 

PROJECT_NAME="SunEngine"
PROJECT_ROOT="auto"
SERVER_PATH="${PROJECT_ROOT}/Server"
CLIENT_PATH="${PROJECT_ROOT}/Client"
CONFIG_PATH="${PROJECT_ROOT}/Config"
BUILD_PATH="${PROJECT_ROOT}/build"
NPM_UTIL="yarn"

