# Variables to build script 

PROJECT_NAME="SunEngine"
PROJECT_ROOT="auto"
SERVER_PATH="${PROJECT_ROOT}/Server"
CLIENT_PATH="${PROJECT_ROOT}/Client"
CONFIG_PATH="${PROJECT_ROOT}/Config"
BUILD_PATH="${PROJECT_ROOT}/build"
NPM_UTIL="yarn"

# Font

RED='\e[0;31m'
GREEN='\e[0;32m'
BLUE='\e[0;34m'
NC='\e[0m'
BOLD='\e[1m'