/* Do not edit this file it is autogenerated  */

const config = {
	// auto-start

	Global: {
		//SiteName: 'SunEngine Demo',
		Locale: "Russian",
		SiteApi: "http://localhost:5000",
		SiteUrl: "http://localhost:5005",
		UploadImagesUrl: "http://localhost:5000/UploadImages",
		SkinsUrl: "http://localhost:5005/statics/Skins",
		PartialSkinsUrl: "http://localhost:5005/statics/PartialSkins",
		CustomCssUrl: "http://localhost:5000/statics/custom.css"
	},
	Dev: {
		VueDevTools: true,
		LogInitExtended: true,
		LogRequests: true,
		LogMoveTo: true
	},

	// auto-end

	PasswordValidation: {
		MinLength: 6,
		MinDifferentChars: 2
	},
	DbColumnSizes: {
		Categories_Name: 64,
		Categories_Title: 256,
		Categories_Token: 64,
		Categories_CustomUrl: Number.MaxValue,
		Categories_SubTitle: Number.MAX_VALUE,
		Categories_Icon: 64,
		Users_UserName: 64,
		Users_Email: 64,
		Users_Link: 64,
		Users_PasswordMinLength: 6,
		Materials_Name: 64,
		Materials_Title: 256,
		Materials_SubTitle: Number.MAX_VALUE,
		Tags_Name: 64,
		Roles_Name: 64,
		Roles_Title: 64,
		OperationKey_Name: 100,
		MenuItems_Name: 64,
		MenuItems_Title: 256,
		MenuItems_SubTitle: Number.MAX_VALUE,
		MenuItems_RouteName: 64,
		MenuItems_CssClass: 64,
		MenuItems_Icon: 64,
		Components_Name: 64,
		Components_Type: 32
	},
	Misc: {
		AdminRoleUsersMaxUsersTake: 40,
		DefaultAvatar: "default-avatar.svg"
	}
};

if (config.Global.SiteUrl.startsWith("http://"))
	config.Global.SiteSchema = "http://";
else if (config.Global.SiteUrl.startsWith("https://"))
	config.Global.SiteSchema = "https://";
else throw "SiteUrl in config.js have to start with 'http://' or 'https://'.";

document.writeln(`<link href="${config.Global.CustomCssUrl}?customcssver=111111" rel="stylesheet" />`);

